### ISSUE TITLE
Author name in footer link to hijiangtao's github page

### ISSUE THREAD

**Issue by elleonard** [hijiangtao/dark-tech#3]
please modify layout/_pertial/footer.ejs L4

`Copyright&copy;2013-<%= new Date().getFullYear() %> <a href="http://hijiangtao.github.io/"><%= config.author %></a>`

to

`Copyright&copy;2013-<%= new Date().getFullYear() %> <a href=" <%= theme.personal_site %>"><%= config.author %></a>`

**Comment by hijiangtao** [comment]
Commit [1bf4c0d](https://github.com/hijiangtao/dark-tech/commit/1bf4c0daa89ff8f045e8d07fdd1380e1280a717f) has fixed the problem you mentioned above, thanks. :-)
