### ISSUE TITLE
Blogroll is constant

### ISSUE THREAD

**Issue by elleonard** [hijiangtao/dark-tech#4]
modify layout/_widget/blogroll.ejs to

```
	<ul class="entry">
	  <% for (var i in theme.blogroll){ %>
	    <li><a href="<%- theme.blogroll[i] %>"><%= i %></a></li>
	  <% } %>
	</ul>
```

and add blogroll config to config.yml

```
blogroll:
  blogtitle: http://blogurl
```

**Comment by hijiangtao** [comment]
Commit [1bf4c0d](https://github.com/hijiangtao/dark-tech/commit/1bf4c0daa89ff8f045e8d07fdd1380e1280a717f) has fixed the problem you mentioned above, thanks a lot. :-)
