### ISSUE TITLE
No pagination with pagination type != 2

### ISSUE THREAD

**Issue by elleonard** [hijiangtao/dark-tech#5]
In layout/_partial/archive.ejs

partial('pagination') is only called when pagination == 2

move
`<%- partial('pagination') %>`
to last line (after if-else block)

**Comment by hijiangtao** [comment]
Sorry about been late to reply the issue and the unexpected mistake, commit [f98054a](https://github.com/hijiangtao/dark-tech/commit/f98054a158ad3e2b345f7e2dad6d1b17b89313b1) had fixed the problem. Thanks.
